image: node:18.18.0
cache:
  paths:
    - node_modules/
stages:
  - deploy
deploy:dev:
  image: ruby:latest
  stage: deploy
  variables:
    APP_NAME: $HEROKU_APP_NAME_DEV
    HEROKU_API_KEY: $HEROKU_API_KEY
  before_script:
    - apt-get update -qy
    - apt-get install -y npm
    - gem install dpl
    - npm install
  script:
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - /^dev-.*$/